### ISSUE TITLE
SyntaxError: Unexpected token ]

### ISSUE THREAD

**Issue by barriehadfield** [ruby-hyperloop/hyper-operation#1]
ExecJS::RuntimeError (prerendering) error after
+ adding the gem
+ adding require 'hyper-operation' to components.rb
+ adding mount Hyperloop::Engine => "/hyperloop_engine" to routes.rb

If I bypass prerender then I get undefined method `path' for nil:NilClass

**Comment by barriehadfield** [comment]
Repo which shows this broken here: https://github.com/barriehadfield/ops-tests

**Comment by barriehadfield** [comment]
Only way around this error for now is to include both engines in `routes.rb`

mount HyperMesh::Engine => '/rr'
mount Hyperloop::Engine => "/hyperloop"

**Comment by adamcreekroad** [comment]
@barriehadfield the problem is HyperOperation isn't yet compatible with HyperMesh. That is what @catmando told me on Friday, I ran into the same problem.

**Comment by dan-klasson** [comment]
Turning off prerendering worked for me. @catmando said he will push fix shortly though

**Comment by catmando** [comment]
I think this is closed... nobody is having problems right?

**Comment by barriehadfield** [comment]
this is gone
