### ISSUE TITLE
Get rid of this annoying message:

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-operation#10]
`DEPRECATION WARNING: #tables currently returns both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only return tables. Use #data_sources instead. (called from needs_init? at /Users/rmitchellvanduyn/rubydev/hyper-operation/lib/hyper-operation/transport/connection.rb:5)`

**Comment by andreysaleba** [comment]
Hi,
I have submitted PR to solve this: https://github.com/ruby-hyperloop/hyper-operation/pull/11

**Comment by catmando** [comment]
@andreysaleba we will be merging your PR with release 0.15 thanks a lot.

**Comment by janbiedermann** [comment]
```
return true if connection.respond_to?(:data_sources) && !connection.data_sources.include?(table_name)
return true if !connection.respond_to?(:data_sources) && !connection.tables.include?(table_name)
```
this is in the code, so i think its fixed
