### ISSUE TITLE
ServerOp on_dispatch can send multiple messages

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-operation#2]
For example

`on_dispatch { Channel::Foo, Channel::Bar }`

if a single client attaches to both Foo and Bar the message will be sent twice.

you can get the same effect as well by doing `2.times { on_dispatch { Channel::Foo} }`
i.e. if the same channel gets dispatched two twice from the same operation

**Comment by janbiedermann** [comment]
i am not sure what you mean here, as `on_dispatch` just adds blocks as receivers and blocks being closures, how to identify they do the same thing for the same binding and exclude them? I dont know.

But for `dispatch_to` i added the following patch to lap21, to make sure it dispatches only once to a channel from one operation run, spec added too:
```ruby
      def dispatch_to(*args, &regulation)
        _dispatch_to(nil, args, &regulation) if RUBY_ENGINE != 'opal'
      end

      def _dispatch_to(context, args=[], &regulation)
        if args.count == 0 && regulation.nil?
          raise "must provide either a list of channel classes or a block to regulate_dispatch"
        elsif args.count > 0 && regulation
          raise "cannot provide both a list of channel classes and a block to regulate_dispatch"
        end
        regulation ||= proc { args }
        on_dispatch do |params, operation|
          operation.instance_variable_set(:@_dispatched_channels, []) unless operation.instance_variable_get(:@_dispatched_channels)
          serialized_params = serialize_dispatch(params.to_h)
          [operation.instance_exec(*context, &regulation)].flatten.compact.uniq.each do |channel|
            unless operation.instance_variable_get(:@_dispatched_channels).include?(channel)
              operation.instance_variable_set(:@_dispatched_channels, operation.instance_variable_get(:@_dispatched_channels) << channel)
              Hyperloop.dispatch(channel: Hyperloop::InternalPolicy.channel_to_string(channel), operation: operation.class.name, params: serialized_params)
            end
          end
        end
      end if RUBY_ENGINE != 'opal'
```

Does that solve the issue?

**Comment by catmando** [comment]
whoops I think there was a typo... That should be `dispatch_to` not `on_dispatch`

sorry you wasted time on this... I don't think there is anything wrong with `on_dispatch`

but it looks like your figured out the truth, and fixed the right place anyway...

**Comment by janbiedermann** [comment]
alright, closure
