### ISSUE TITLE
Issue with broadcasting to the current_session

### ISSUE THREAD

**Issue by psmir** [ruby-hyperloop/hyper-operation#26]
```
class App < Hyperloop::Component
  after_mount :connect_session
end
```
This gives me an error: 

> Exception raised while rendering #<App:0x776>: undefined method `connect_session' for Object

**Comment by catmando** [comment]
My box is dead so I can't give a detailed response on my phone.  Connect_seesion is a class method on the Hyperloop module so u want

```ruby
after_mount { Hyperloop.connect_session }
```

But in general u don't have to manually connect.

Lots of help live over on https://gitter.im/ruby-hyperloop/chat
