### ISSUE TITLE
Get a Rails error when using mount Hyperloop::Engine => '/hyperloop'

### ISSUE THREAD

**Issue by fzingg** [ruby-hyperloop/hyper-operation#3]
Hyperloop Gem version (e9b83bfa6bea)
Rails version (5.0.2)

When using mount `Hyperloop::Engine => '/rr' everything` works well.
When using mount `Hyperloop::Engine => '/hyperloop'`

I got the error:

```
ActionController::RoutingError (No route matches [GET] "/rr/hyperloop-read/2bd082bb-3452-4bab-b206-af440493e67f-26b7b23137ba510a0f1a06535630a123"):
```

**Comment by catmando** [comment]
cannot reproduce... please try again and close if you confirm its not a problem
