### ISSUE TITLE
Need to be able to set Pusher cluster in config

### ISSUE THREAD

**Issue by adamcreekroad** [ruby-hyperloop/hyper-operation#5]
When creating a Pusher app you have to choose your cluster. The original cluster is 'mt1', so any **older** app works. But new clusters default to 'us2', so they are currently unusable.

If you try to use a Pusher app from another cluster you get this error message in the console:
```javascript
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4001,"message":"Did you forget to specify the cluster when creating the Pusher instance?  App key abc.......... does not exist in this cluster."}}}
```

Should hopefully be as simple as adding that as a config option that defaults to 'mt1', and then having that sent up to the JS Pusher initialization.

Should also include the latest pusher JS source (v4.0).

**Comment by catmando** [comment]
closed.  You can now specify the cluster in the hyperloop config
```ruby
Hyperloop.configuration do |config| 
  config.transport = :pusher
  config.cluster = 'mt2' # defaults to 'mt1'
end
```
