### ISSUE TITLE
normalization the use about operation run.

### ISSUE THREAD

**Issue by zw963** [ruby-hyperloop/hyper-operation#9]
current, one operation is run by following way:

1.  MessagesOperations::Send.run(message: state.message_field)
2. MessagesOperations::Send(message: state.message_field)
3. MessagesOperations::GetMessages.run

I think this is weird when a newbie use this first time.

I think it should better in document, use only one form:

- all `.run`, regardless of if exist params args
- all not use `run`, though, this form some little strange. e.g. ` MessagesOperations::GetMessages()`.

**Comment by zw963** [comment]
current, tuto, some example use `run`, some example use camelcase method, it confuse me a lot.

**Comment by zw963** [comment]
My prefer usage is: 

```rb
MessagesOperations::GetMessages()
MessagesOperations::Send(message: 'new_message')
```

because `.run` is too universal, we write `run` method in others components 
some case. but, `camelcase with ()` is special, that good for operations, even 
we can create a convention, that, `operations need be run with only one form:
ThisIsAOp()`, that good for even we can use any name which does not include
'Op' suffix.

**Comment by catmando** [comment]
Actually the majority wants to drop the () in favor of .run().  In addition it simplifies the code a lot.

**Comment by janbiedermann** [comment]
done in sachsenring lap5

**Comment by barriehadfield** [comment]
The docs are already in line with this change.

**Comment by zw963** [comment]
Cool.
